import React from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '../components/ui/button';
import { Card } from '../components/ui/card';
import { SparklesIcon, TargetIcon, TrendingUpIcon, ClockIcon, CheckIcon } from '../components/icons';
import { cn } from '../lib/utils';

/* ═══════════════════════════════════════════════════════════════
   LANDING PAGE - Phase 9.4 Page Redesign

   Marketing landing page for new users.
   Uses design tokens for consistent styling.
   ═══════════════════════════════════════════════════════════════ */

interface LandingPageProps {
  onGetStarted: () => void;
  onSignIn: () => void;
}

export default function LandingPage({ onGetStarted, onSignIn }: LandingPageProps) {
  const { t } = useTranslation();

  const features = [
    {
      icon: SparklesIcon,
      title: 'AI-Powered Plans',
      description:
        'Get personalized workout plans generated by AI based on your goals, experience, and equipment.',
    },
    {
      icon: TargetIcon,
      title: 'Goal-Focused Training',
      description:
        'Whether you want to build muscle, lose fat, or prepare for a sport, we adapt to your goals.',
    },
    {
      icon: TrendingUpIcon,
      title: 'Track Progress',
      description: 'Log workouts, track PRs, and visualize your progress with detailed analytics.',
    },
    {
      icon: ClockIcon,
      title: 'Flexible Scheduling',
      description: 'Train 2 days or 6 days a week. Your plan adjusts to fit your lifestyle.',
    },
  ];

  const benefits = [
    'Parse any workout plan instantly',
    'AI coaching that pushes you',
    'Exercise explanations & form cues',
    'Superset & AMRAP support',
    'Track sets, reps, and weight',
    'Free to start',
  ];

  return (
    <div className={cn('min-h-screen', 'bg-[var(--bg-primary)]', 'flex flex-col')}>
      {/* Header */}
      <header
        className={cn(
          'px-[var(--space-4)] py-[var(--space-4)]',
          'flex items-center justify-between',
          'max-w-5xl mx-auto w-full'
        )}
      >
        <div className="font-display text-[var(--text-xl)] font-[var(--weight-black)] logo-spacing">
          <span className="text-[var(--text-primary)]">RE</span>
          <span className="text-[var(--brand-primary)]">BLD</span>
        </div>
        <button
          onClick={onSignIn}
          className={cn(
            'text-[var(--text-sm)]',
            'font-[var(--weight-semibold)]',
            'text-[var(--text-secondary)]',
            'hover:text-[var(--text-primary)]',
            'transition-colors duration-[var(--duration-fast)]'
          )}
        >
          Sign In
        </button>
      </header>

      {/* Hero Section */}
      <main className="flex-1 px-[var(--space-4)] py-[var(--space-8)] sm:py-[var(--space-8)]">
        <div className="max-w-5xl mx-auto">
          {/* Hero */}
          <div className="text-center mb-[var(--space-8)] sm:mb-[var(--space-8)]">
            <h1
              className={cn(
                'font-display',
                'text-[var(--text-3xl)] sm:text-[3rem] lg:text-[3.75rem]',
                'font-[var(--weight-black)]',
                'text-[var(--text-primary)]',
                'tracking-tight',
                'mb-[var(--space-4)]',
                'leading-tight'
              )}
            >
              Your AI Training Partner
            </h1>
            <p
              className={cn(
                'text-[var(--text-lg)] sm:text-[var(--text-xl)]',
                'text-[var(--text-secondary)]',
                'max-w-2xl mx-auto',
                'mb-[var(--space-8)]',
                'leading-relaxed'
              )}
            >
              Get personalized workout plans, intelligent coaching, and progress tracking. Paste any
              workout plan and we'll parse it instantly.
            </p>
            <div
              className={cn(
                'flex flex-col sm:flex-row',
                'gap-[var(--space-4)]',
                'justify-center items-center'
              )}
            >
              <Button
                onClick={onGetStarted}
                variant="accent"
                className={cn(
                  'w-full sm:w-auto',
                  'px-[var(--space-8)] py-[var(--space-3)]',
                  'text-[var(--text-base)]'
                )}
              >
                Get Started Free
              </Button>
              <p className={cn('text-[var(--text-sm)]', 'text-[var(--text-tertiary)]')}>
                No credit card required
              </p>
            </div>
          </div>

          {/* Features Grid */}
          <div
            className={cn(
              'grid sm:grid-cols-2 lg:grid-cols-4',
              'gap-[var(--space-4)]',
              'mb-[var(--space-8)] sm:mb-[var(--space-8)]'
            )}
          >
            {features.map((feature, index) => (
              <Card key={index} variant="soft" className="p-[var(--space-5)]">
                <div
                  className={cn(
                    'w-10 h-10',
                    'rounded-[var(--radius-xl)]',
                    'bg-[var(--brand-primary-subtle)]',
                    'flex items-center justify-center',
                    'mb-[var(--space-4)]'
                  )}
                >
                  <feature.icon className="w-5 h-5 text-[var(--brand-primary)]" />
                </div>
                <h3
                  className={cn(
                    'font-[var(--weight-bold)]',
                    'text-[var(--text-primary)]',
                    'mb-[var(--space-2)]'
                  )}
                >
                  {feature.title}
                </h3>
                <p
                  className={cn(
                    'text-[var(--text-sm)]',
                    'text-[var(--text-secondary)]',
                    'leading-relaxed'
                  )}
                >
                  {feature.description}
                </p>
              </Card>
            ))}
          </div>

          {/* Benefits List */}
          <div
            className={cn(
              'max-w-xl mx-auto',
              'mb-[var(--space-8)] sm:mb-[var(--space-8)]'
            )}
          >
            <h2
              className={cn(
                'font-display',
                'text-[var(--text-xl)]',
                'font-[var(--weight-bold)]',
                'text-[var(--text-primary)]',
                'text-center',
                'mb-[var(--space-6)]'
              )}
            >
              Everything you need to train smarter
            </h2>
            <div className="grid sm:grid-cols-2 gap-[var(--space-3)]">
              {benefits.map((benefit, index) => (
                <div
                  key={index}
                  className={cn(
                    'flex items-center gap-[var(--space-3)]',
                    'p-[var(--space-3)]',
                    'rounded-[var(--radius-xl)]',
                    'bg-[var(--surface-primary)]'
                  )}
                >
                  <div
                    className={cn(
                      'w-6 h-6',
                      'rounded-full',
                      'bg-[var(--status-success-bg)]/20',
                      'flex items-center justify-center',
                      'flex-shrink-0'
                    )}
                  >
                    <CheckIcon className="w-3.5 h-3.5 text-[var(--status-success-bg)]" />
                  </div>
                  <span
                    className={cn(
                      'text-[var(--text-sm)]',
                      'font-[var(--weight-medium)]',
                      'text-[var(--text-primary)]'
                    )}
                  >
                    {benefit}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* CTA Section */}
          <div
            className={cn(
              'text-center',
              'bg-[var(--surface-primary)]',
              'border border-[var(--border-default)]',
              'rounded-[var(--radius-2xl)]',
              'p-[var(--space-8)] sm:p-[var(--space-8)]'
            )}
          >
            <h2
              className={cn(
                'font-display',
                'text-[var(--text-xl)] sm:text-[var(--text-2xl)]',
                'font-[var(--weight-bold)]',
                'text-[var(--text-primary)]',
                'mb-[var(--space-3)]'
              )}
            >
              Ready to transform your training?
            </h2>
            <p
              className={cn(
                'text-[var(--text-secondary)]',
                'mb-[var(--space-6)]',
                'max-w-md mx-auto'
              )}
            >
              Join thousands of athletes who are training smarter with AI-powered workouts.
            </p>
            <Button
              onClick={onGetStarted}
              variant="accent"
              className={cn('px-[var(--space-8)] py-[var(--space-3)]', 'text-[var(--text-base)]')}
            >
              Start Training Now
            </Button>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer
        className={cn(
          'px-[var(--space-4)] py-[var(--space-6)]',
          'border-t border-[var(--border-default)]'
        )}
      >
        <div
          className={cn(
            'max-w-5xl mx-auto',
            'flex flex-col sm:flex-row',
            'items-center justify-between',
            'gap-[var(--space-4)]'
          )}
        >
          <p className={cn('text-[var(--text-sm)]', 'text-[var(--text-tertiary)]')}>
            © 2025 REBLD. All rights reserved.
          </p>
          <div className="flex items-center gap-[var(--space-4)]">
            <span className={cn('text-[var(--text-sm)]', 'text-[var(--text-tertiary)]')}>
              Already have an account?
            </span>
            <button
              onClick={onSignIn}
              className={cn(
                'text-[var(--text-sm)]',
                'font-[var(--weight-semibold)]',
                'text-[var(--brand-primary)]',
                'hover:text-[var(--brand-primary-hover)]',
                'transition-colors duration-[var(--duration-fast)]'
              )}
            >
              Sign In
            </button>
          </div>
        </div>
      </footer>
    </div>
  );
}
